name: Build and Push Docker Image
on:
  push:
    paths:
      - Dockerfile
      - app.py
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker build -t myapp .
          docker tag myapp:latest 062413611684.dkr.ecr.us-east-1.amazonaws.com/app:latest
          docker push 062413611684.dkr.ecr.us-east-1.amazonaws.com/app:latest

